export const definiciones = {
  "Porcentaje de mujeres en edad fértil que su último parto fue atendido por personal de salud calificado(1).":
    {
      texto: "Porcentaje de mujeres de 15 a 49 años de edad que tuvieron hijos durante los últimos cinco años y cuyo parto fue atendido por personal de salud calificado",
      abreviacion: "Atención del parto",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [40, 100],
      format: ".0f",
    },
  "Paridez media de mujeres de 15 a 19 años de edad.": {
    texto: "Promedio de hijos nacidos vivos entre mujeres de 15 a 19 años de edad",
    abreviacion: "Paridez adolescente",
    colormap: [
      "#69b17c",
      "#69c2af",
      "#b6dbeb",
      "#dfe8f3",
      "rgba(182, 178, 235, 1)",
    ],
    domain: [0, 0.7],
    format: ".1f",
  },
  "Población con Cobertura de Salud(2).": {
    texto: "Porcentaje de la población cubierta por el Sistema Único de Salud y otros seguros de salud",
    abreviacion: "Cobertura de salud",
    colormap: [
      "rgba(182, 178, 235, 1)",
      "#dfe8f3",
      "#dfe8f3",
      "#b6dbeb",
      "#69c2af",
      "#69b17c",
    ],
    domain: [40, 100],
    format: ".0f",
  },
  "Porcentaje de niñas, niños y adolescentes de 12 a 17 años de edad que completaron al menos 6 años de escolaridad e índice de paridad.":
    {
      texto: "Porcentaje de niñas, niños y adolescentes de 12 a 17 años de edad que completaron al menos 6 años de escolaridad",
      abreviacion: "Escolaridad 12-17 años",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [70, 100],
      format: ".0f",
    },
  "Tasa de asistencia a un establecimiento educativo de niñas y niños de 4 a 5 años de edad e índice de paridad.":
    {
      texto: "Porcentaje de niños de 4 a 5 años que asisten a un establecimiento educativo",
      abreviacion: "Asistencia preescolar",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [40, 100],
      format: ".0f",
    },
  "Porcentaje de población de 15 a 24 años de edad que completó primaria e índice de paridad.":
    {
      texto: "Porcentaje de población de 15 a 24 años de edad que completó la primaria",
      abreviacion: "Primaria completa 15-24 años",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [70, 100],
      format: ".0f",
    },
  "Porcentaje de población de 19 o más años de edad que completó primaria e índice de paridad.":
    {
      texto: "Porcentaje de población de 19 o más años de edad que completó la primaria",
      abreviacion: "Primaria completa adultos",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [30, 100],
      format: ".0f",
    },
  "Porcentaje de la población con acceso a fuente mejorada de agua.": {
    texto: "Porcentaje de la población con acceso a una fuente mejorada de agua",
    abreviacion: "Acceso a agua",
    colormap: [
      "rgba(182, 178, 235, 1)",
      "#dfe8f3",
      "#dfe8f3",
      "#b6dbeb",
      "#69c2af",
      "#69b17c",
    ],
    domain: [25, 100],
    format: ".0f",
  },
  "Porcentaje de la población con acceso a servicio de saneamiento gestionados de manera segura.":
    {
      texto: "Porcentaje de la población con acceso a saneamiento gestionado de manera segura",
      abreviacion: "Saneamiento seguro",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [15, 100],
      format: ".0f",
    },
  "Porcentaje de la población con acceso a energía eléctrica.": {
    texto: "Porcentaje de la población con acceso a energía eléctrica",
    abreviacion: "Energía eléctrica",
    colormap: [
      "rgba(182, 178, 235, 1)",
      "#dfe8f3",
      "#dfe8f3",
      "#b6dbeb",
      "#69c2af",
      "#69b17c",
    ],
    domain: [40, 100],
    format: ".0f",
  },
  "Porcentaje de la población que utiliza combustibles limpios (no sólidos) para cocinar.":
    {
      texto: "Porcentaje de la población que utiliza combustibles limpios (no sólidos) para cocinar",
      abreviacion: "Combustibles limpios",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [20, 100],
      format: ".0f",
    },
  "Porcentaje de población de 14 o más años de edad ocupada en actividades económicas relacionadas con el turismo.":
    {
      texto: "Porcentaje de población de 14 o más años de edad ocupada en actividades económicas relacionadas con el turismo",
      abreviacion: "Empleo en turismo",
      colormap: ["#dfe8f3", "#b6dbeb", "#69c2af", "#69b17c"],
      domain: [0, 12],
      format: ".0f",
    },
  "Porcentaje de población de 14 o más años de edad ocupada en la industria manufacturera.":
    {
      texto: "Porcentaje de población de 14 o más años de edad ocupada en la industria manufacturera",
      abreviacion: "Empleo manufacturero",
      colormap: ["#dfe8f3", "#b6dbeb", "#69c2af", "#69b17c"],
      domain: [0, 19],
      format: ".0f",
    },
  "Porcentaje de hogares que tienen teléfono celular.": {
    texto: "Porcentaje de hogares con teléfono celular",
    abreviacion: "Telefonía celular",
    colormap: [
      "rgba(182, 178, 235, 1)",
      "#dfe8f3",
      "#dfe8f3",
      "#b6dbeb",
      "#69c2af",
      "#69b17c",
    ],
    domain: [60, 100],
    format: ".0f",
  },
  "Porcentaje de hogares que tienen internet.": {
    texto: "Porcentaje de hogares con internet",
    abreviacion: "Internet",
    colormap: [
      "rgba(182, 178, 235, 1)",
      "#dfe8f3",
      "#b6dbeb",
      "#69c2af",
      "#69b17c",
    ],
    domain: [25, 100],
    format: ".0f",
  },
  "Porcentaje de niñas y niños menores de 5 años de edad con inscripción de su nacimiento en el registro civil boliviano.":
    {
      texto: "Porcentaje de niñas y niños menores de 5 años de edad cuyo nacimiento fue inscrito en el registro civil boliviano",
      abreviacion: "Registro de nacimiento",
      colormap: [
        "rgba(182, 178, 235, 1)",
        "#dfe8f3",
        "#b6dbeb",
        "#69c2af",
        "#69b17c",
      ],
      domain: [75, 100],
      format: ".0f",
    },
  "Porcentaje de mujeres de 20 a 24 años de edad que tuvieron su primer hijo antes de los 20 años(2).":
    {
      texto: "Porcentaje de mujeres de 20 a 24 años de edad que tuvieron su primer hijo antes de cumplir los 20 años",
      abreviacion: "Maternidad adolescente",
      colormap: [
        "#69b17c",
        "#69c2af",
        "#b6dbeb",
        "#dfe8f3",
        "rgba(182, 178, 235, 1)",
      ],
      domain: [0, 8],
      format: ".0f",
    },
};
