name: Publicar
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: publicar
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: setup docs
      run: |
        mkdir -p docs
        touch docs/.nojekyll

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: ./vista/package-lock.json

    - name: dependencias
      working-directory: ./vista
      run: npm ci

    - name: build
      working-directory: ./vista
      run: npm run build

    - name: ensure .nojekyll
      run: touch ./docs/.nojekyll

    - name: publicar
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs